// ENTITY_OBJECT = OBJECT_NAME
// Auth
const AUTH_AUTH = 'Auth';
// Hearbeat
const HEARTBEAT_NEXT_SHOW = 'NextShow';
const HEARTBEAT_PLAYER = 'Player';
const HEARTBEAT_SCHEDULES = 'Schedules';
const HEARTBEAT_SETTINGS_PROFILE = 'SettingsProfile';
const HEARTBEAT_CINE_CARD_EXECUTABLE = 'CineCardExecutable';
const HEARTBEAT_SCREEN = 'Screen';
const HEARTBEAT_DEFAULT_PLAYLIST = 'DefaultPlaylist';
const HEARTBEAT_BLOCK = 'Block';
const HEARTBEAT_GAMES = 'Games';
const HEARTBEAT_TARGETS = 'Targets';
const HEARTBEAT_PLAYLIST = 'Playlist';
// Logs
const LOGS_LOGS = 'Logs';
// Network Config
const NETWORKCONFIG_NETWORK_CONFIG = 'NetworkConfig';
const NETWORKCONFIG_DHCP_OVERRIDE = 'DHCPOverride';
const NETWORKCONFIG_SYSTEM_MAC = 'SystemMac';
const NETWORKCONFIG_NETWORK_INTERFACE = 'NetworkInterface';
const MACHINE_MACHINE = 'Machine';

module.exports = {
  AUTH_AUTH,
  HEARTBEAT_NEXT_SHOW,
  HEARTBEAT_PLAYER,
  HEARTBEAT_SCHEDULES,
  HEARTBEAT_SETTINGS_PROFILE,
  HEARTBEAT_CINE_CARD_EXECUTABLE,
  HEARTBEAT_SCREEN,
  HEARTBEAT_DEFAULT_PLAYLIST,
  HEARTBEAT_BLOCK,
  HEARTBEAT_GAMES,
  HEARTBEAT_TARGETS,
  HEARTBEAT_PLAYLIST,
  LOGS_LOGS,
  NETWORKCONFIG_NETWORK_CONFIG,
  NETWORKCONFIG_DHCP_OVERRIDE,
  NETWORKCONFIG_SYSTEM_MAC,
  NETWORKCONFIG_NETWORK_INTERFACE,
  MACHINE_MACHINE,
};
