name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Package
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - name: Install yarn
        run:  npm install --global yarn
      - name: Install Electron Packager
        run: npm i -g electron-packager
      - name: Install Electron Installer Debian
        run: npm i -g electron-installer-debian
      - name: Install fakeroot
        run: sh scripts/install.sh
      - name: Install node modules
        run:  npm i --legacy-peer-deps
      - name: Add Sentry DSN
        run: echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
      - name: Run build
        run:  npm run build:linux
      - name: Package
        run: npm run package:linux 
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/app/release-builds/installers
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "build-artifact.zip"
          folderId: ${{ secrets.folderId }}
          name: "build-artifact" # optional string
          overwrite: "true" # optional boolean
      - name: Make Directory Structure
        run: |
          mkdir -p w/x/y
          date +%s > w/x/y/z    
